# -*- coding: utf-8 -*-
"""Agricultura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNy2mPgmc9XFux99v7hDVO4OWtfxdrQA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

file_path = 'https://drive.google.com/uc?export=download&id=1z_4GVdK0mrGKpX4Y3ZO9IK9w39_o0XN7'
data = pd.read_csv(file_path)

print("Dataset Information:")
print(data.info())

print("\nBasic Statistics:")
print(data.describe(include='all'))

print("\nMissing Values:")
print(data.isnull().sum())

plt.figure(figsize=(12, 6))
sns.heatmap(data.isnull(), cbar=False, cmap='viridis')
plt.title("Heatmap of Missing Values")
plt.show()

numerical_columns = data.select_dtypes(include=['float64', 'int64']).columns
numerical_columns

categorical_columns = data.select_dtypes(include=['object']).columns
categorical_columns


data_cleaned = data.dropna(thresh=0.8*len(data), axis=1)

data_cleaned.head()

plt.figure(figsize=(12, 6))
sns.heatmap(data_cleaned.isnull(), cbar=False, cmap='viridis')
plt.title("Heatmap of Missing Values")
plt.show()

print("\nMissing Values:")
print(data_cleaned.isnull().sum())

data_cleaned.to_csv('https://drive.google.com/uc?export=download&id=1z_4GVdK0mrGKpX4Y3ZO9IK9w39_o0XN7', index=False)
print("\nCleaned dataset saved.")

df = pd.read_csv('https://drive.google.com/uc?export=download&id=1z_4GVdK0mrGKpX4Y3ZO9IK9w39_o0XN7')

missing_values = df.isnull().sum()

threshold = 0.5
columns_to_drop = missing_values[missing_values / len(df) > threshold].index

df_cleaned = df.drop(columns=columns_to_drop)

df_cleaned = df_cleaned.ffill()

# df_cleaned = df_cleaned.bfill()
# df_cleaned.fillna(df_cleaned.mean(), inplace=True)

print("Missing values after cleaning:")
print(df_cleaned.isnull().sum())

plt.figure(figsize=(12, 6))
sns.heatmap(df_cleaned.isnull(), cbar=False, cmap='viridis')
plt.title("Heatmap of Missing Values")
plt.show()

df_cleaned.to_csv('https://drive.google.com/uc?export=download&id=1z_4GVdK0mrGKpX4Y3ZO9IK9w39_o0XN7', index=False)
print("\nCleaned dataset saved.")